name: E2E test
on:
  workflow_dispatch:
# push:
#   tags:
#     # 通常リリース: 例) v1.2.3
#     - "v[0-9]+.[0-9]+.[0-9]+"
#     # プリリリースのみ: 例) v1.2.3-rc.1, v1.2.3-beta など(必ず '-' が付く)
#     - "v[0-9]+.[0-9]+.[0-9]+-*"

defaults:
  run:
    shell: bash

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests_e2e:
    if: github.repository_owner == github.actor
    ## Only run if pushed by repository owner and after OSV scan passes...
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          # version: latest. ## package.json の packageManagerに従う
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright browsers
        run: npx playwright install chromium

      - name: "INFO: Show tool versions"
        run: node -v && npm -v && pnpm -v && playwright --version && playwright install --list

      - name: Run E2E test
        run: pnpm test:e2e
